### ISSUE TITLE
unaligned memory access on 64-bit SPARC during module initialization

### ISSUE THREAD

**Issue by glenk** [OpenIDC/ngx_oauth2_module#2]
When starting up nginx built with the ngx_oauth2_module on 64-bit SPARC (niagara4) on Solaris 10 with gcc 5.5.0, nginx dumps core with a SIGBUS error:

Program terminated with signal SIGBUS, Bus error.
#0  0x0000000100166f54 in ngx_openidc_set_claim (cf=0xffffffff7ffff480, 
    cmd=0x1002efe70 <ngx_openidc_commands+336>, conf=0x100370380)
    at /home/webops/myghadm/src/ngx_openidc_module-master/src/ngx_openidc_module.c:144
144             claim->name = oauth2_strndup((const char *)value[1].data, value[1].len);

As SPARC is sensitive to alignment issues, I expect that this is a platform-specific issue.

My OpenIDC config (redacted, from the server location section of a very generic nginx.conf) is attached at OpenIDC-Config.txt.

The stack trace from the core file is attached as gdb_ngx_core.txt. 

I'm happy to provide any additional information on this issue, and any further assistance to help resolve this.
Thanks for taking a look!

[OpenIDC-Config.txt](https://github.com/zmartzone/ngx_oauth2_module/files/6559307/OpenIDC-Config.txt)
[gdb_ngx_core.txt](https://github.com/zmartzone/ngx_oauth2_module/files/6559308/gdb_ngx_core.txt)

**Comment by zandbelt** [comment]
hmm, can you use "-misalign" as a compiler option?

also, the stack trace seems to be about `ngx_openidc_module` rather than `ngx_oauth2_module`?

**Comment by glenk** [comment]
Hi Hans,

I’m sorry, I missed your note when I was out last Friday.  I’m using gcc 5.5, and that doesn’t seem to be a command-line option recognized by gcc.  The output from nginx auto/configure reports:

gcc: error: unrecognized command line option '-misalign'

Would it help to switch to the Oracle (formerly Sun) Studio developer compiler?  Are there other gcc flags that would help?

Thanks!
-glen

**Comment by zandbelt** [comment]
please try https://github.com/zmartzone/ngx_openidc_module/commit/1d886282b9042814d66a802e7a60c5bbf20b7a45 and https://github.com/zmartzone/ngx_oauth2_module/commit/3309c78e389c3ec28630e8ec0f37d963b74f6e22
