### ISSUE TITLE
 Unable to start the nginx service (/etc/nginx/modules/liboauth2.so: undefined symbol: ngx_modules) in /etc/nginx/nginx.conf

### ISSUE THREAD

**Issue by vijiv6190** [OpenIDC/ngx_oauth2_module#5]
Hi,

I am trying to enable oauth2 for nginx proxy services. I have installed and configured nginx_oauth2_module using the below instructions. I have all the dependencies installed. After adding oAuth2 configurations in nginx.conf unable to restart the nginx service. I am getting below error. Please help me troubleshoot the issue. 

https://github.com/OpenIDC/ngx_oauth2_module

nginx.conf:

location /oauth2/pingfed/introspect {
            OAuth2TokenVerify $source_token introspect 
                https://pingfed:9031/as/introspect.oauth2
                introspect.ssl_verify=false&introspect.auth=client_secret_basic&client_id=rs0&client_secret=2Federate;

            OAuth2Claim sub $pfc_introspect_sub;
            OAuth2Claim username $pfc_introspect_username;
            OAuth2Claim active $pfc_introspect_active;

            proxy_set_header OAUTH2_CLAIM_sub $pfc_introspect_sub;
            proxy_set_header OAUTH2_CLAIM_username $pfc_introspect_username;
            proxy_set_header OAUTH2_CLAIM_active $pfc_introspect_active;
            proxy_pass http://echo:8080/headers$is_args$args;
        }

Error:
 [emerg] 1960146#1960146: dlsym() "/etc/nginx/modules/liboauth2.so", "ngx_modules" failed (/etc/nginx/modules/liboauth2.so: undefined symbol: ngx_modules) in /etc/nginx/nginx.conf:13

**Comment by zandbelt** [comment]
that is probably a mismatch between the stock NGINX version for your platform and the one that you've installed

**Comment by vijiv6190** [comment]
The nginx version that I have is 1.22.1. Is it not compatible? Which version I need to use

**Comment by zandbelt** [comment]
I meant the runtime NGINX must be the same version as the one (from sources) that you compile against
