### ISSUE TITLE
How to compile this from source

### ISSUE THREAD

**Issue by fostermi** [OpenIDC/ngx_oauth2_module#6]
Hans,

I'm trying to compile this module from source as the .deb packages are for a pretty older version of nginx (trying to install and use them on the default nginx docker container of bookworm gives an error regarding "version X instead of Y"). However, after fumbling about for days of trial and error I just can seem to get a .so file from following your workflow script in github or I get configure or make errors when trying to follow the official nginx documentation on compiling dynamic modules.  Any help would be appreciated.

**Comment by zandbelt** [comment]
I don't think I can add more than what is in here: https://github.com/OpenIDC/ngx_oauth2_module/blob/master/.github/workflows/build.yml#L20-L34
