### ISSUE TITLE
variable colision between requests

### ISSUE THREAD

**Issue by pladen** [OpenIDC/ngx_oauth2_module#8]
First, thanks for these modules. I have some Apache servers which work flawlessly for months.
I have to port some of my traffic to nginx on RHEL9, so I'm testing the ngx-oauth2 module.

My lab setup is just the translated apache one :
```
 location /protected {
          OAuth2TokenVerify $source_token metadata https://cognito-idp.eu-west-1.amazonaws.com/XXX/.well-known/openid-configuration verify.iat=skip ;

          add_header X-USER $jwt_username ;

          OAuth2Claim sub $jwt_sub;
          OAuth2Claim cognito:username $jwt_username;
          OAuth2Claim email $jwt_email;
          OAuth2Claim token_use $jwt_token_use;

          proxy_pass ...
}
```

Test with token is fine
```
curl "rhel9-ci:8080/protected/?$RANDOM" -H "Authorization: bearer $TOKEN" -iI
HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Mon, 17 Jun 2024 21:48:00 GMT
Content-Type: text/html
Content-Length: 15
Last-Modified: Mon, 17 Jun 2024 17:43:16 GMT
Connection: keep-alive
ETag: "667075b4-f"
X-USER: mycognito.myuser
Accept-Ranges: bytes
```
However env variables keep set on next request, even without token
```
curl "rhel9-ci:8080/protected/?$RANDOM" -iI
HTTP/1.1 200 OK
...
X-USER: mycognito.myuser
```
In debug mode I can see this when no token provided

```
[debug] 15738#15738: *73 # ngx_oauth2_handler: ngx_http_complex_value ngx_source_token.len=0
[debug] 15738#15738: *73 # ngx_oauth2_handler: leave: -5
...
[debug] 15738#15738: *73 ngx_oauth2_claim_variable: cognito:username=xxxx
[debug] 15738#15738: *73 http script var: "xxxx"
```
So i suspect that some context is not freed between requests, and variables value are kept from one run to another.
Does someone have an hint ?

My env
```
Red Hat Enterprise Linux release 9.4 (Plow)
cjose-0.6.2.3-1.el9.x86_64
liboauth2-1.6.2-1.el9.x86_64
liboauth2-nginx-1.6.2-1.el9.x86_64
nginx-1.20.1-14.el9_2.1.x86_64
nginx-core-1.20.1-14.el9_2.1.x86_64
nginx-filesystem-1.20.1-14.el9_2.1.noarch
nginx-mod-oauth2-3.4.0-1.el9.x86_64
```

**Comment by zandbelt** [comment]
looks like you're running into https://github.com/OpenIDC/ngx_oauth2_module/pull/7 ?

**Comment by pladen** [comment]
thanks for your so quick answer
indeed, same issue.
the PR seems good for you, do you plan to merge it any time soon ?

**Comment by zandbelt** [comment]
I'll start working on integrating this code into liboauth2

**Comment by pladen** [comment]
Good to hear. I'll keep monitor this PR and will test it once it is ready.
Thanks for the good work !

**Comment by pladen** [comment]
Man you're the faster OSS dev I've ever seen, thanks !

**Comment by pladen** [comment]
I've just tested it on debian bullseye, and it works as expected.

- Invalid JWT => 401
- Valid JWT => 200
- Complex rules with OAuth2Require and maps work too

BTW I didnt manage to test on RHEL because I didn't find any SPEC file or way to build RPM. Do you provide it somewhere ?

Great job !

**Comment by zandbelt** [comment]
thanks, but no need to test on other platforms, we have added a test in our CI/CD environment that runs on all platforms for which we provide packages in the Assets section of a release
